export default [
  'sole female',
  'sole male',
  'multi-work series',
  'unlimited',
  'partial censorship',
  'full censorship',
  'mosaic censorship',
  'censored',
  'secret crush',
  'dilf',
  'big dick',
  'already uploaded',
  'sudden appearance',
  'large dicks',
  'tankoubon',
  'bbm',
  'big penis',
  'sister complex',
  'aunt',
  'niece',
  'daughter',
  'step-mother/step-son relationship',
  'schoolboy uniform',
  'big areolae',
  'kissing',
  'bathroom intercourse',
  'old man',
  'bald',
  'serialized',
  'collection of short stories/oneshots',
  'oneshot',
  'son complex',
  'ugly bastard',
  'japan',
  'earth',
  'erotic game',
  'asia',
  'blur-ray',
  'freckles',
  'present',
  'sex',
  'small breasts',
  'poro petit',
  'nudity',
  'suicide',
  'visual novel',
  'fancy realize media',
  'bitch',
  'collaboration works',
  'flashback',
  'water sex',
  'pseudo blowjob',
  'teacher x student',
  'teacher-student relationship',
  'pink pineapple',
  'mary jane',
  'enjoyable rape',
  'otaku culture',
  'merchandising show',
  'idol',
  'doggy style',
  'selfish',
  'manga',
  'licking',
  'queen bee',
  'comedy',
  'exclusive',
  'strappado',
  'new',
  'bishop',
  'bunnywalker',
  't-rex',
  '1080p',
  'bishoujo',
  'non-blood-related siblings',
  'princess',
  'blonde',
  'juicymango',
  'bootleg',
  'high school',
  'mobile phone',
  'school life',
  'tragedy',
  'ziz',
  'milkshake',
  'hd',
  'tsundere',
  'super power',
  'confession',
  'discontinued',
  'revenge',
  'vanilla series',
  'foreplay',
  'incomplete story',
  'toilet',
  'milky',
  'animan',
  'calling your attacks',
  'french kiss',
  'girl kissing girl',
  'girl rapes girl',
  'martial arts',
  'past',
  'pussy sandwich',
  'slapstick',
  'vulgar at times',
  'time travel',
  'pussy sandwich',
  'girlstalk',
  'green bunny',
  'magic',
  'half-length episodes',
  'infidelity',
  'point of view',
  'pink pineapple',
  'urophagia',
  'nur',
  'poro',
  'modern',
  'fantasy',
  'chichinoya',
  'window fuck',
  'glass',
  'chocolat',
  'bomb! cute! bomb!',
  'suzuki mirano',
  'discovery',
  'pov',
  'edge',
  'antechinus',
  'dwarfsoft',
  'gymnastics',
  'shibari',
  'train',
  'anal pissing',
  'aphrodisiac',
  'violence',
  'marathon',
  'bomb! cute!bomb!',
  'everybody has sex',
  'under one roof',
  'horror',
  'post-apocalypse',
  'action',
  'fantasy',
  'fantasy world',
  'swordplay',
  'pixy',
  'climax',
  'swimming',
  'sports',
  'damsel in distress',
  'multi-segment episodes',
  'multiple personality disorder',
  'school intercourse',
  'perverts',
  'aggressive lover',
  'feminization',
  'osananajimi',
  'shimapan',
  'aunt-nephew relationship',
  'cousins',
  'mother complex',
  'porn stars',
  'oppai loli',
  'mother and daughter',
  'cousin',
  'tutor',
  'prolapse',
  'neighbors',
  'poor grammar',
  'gyaru-oh',
  'double vaginal',
  'debts',
  'uncle and niece'
];
