export default new Map<string, string>([
  ['full color', 'full colour'],
  ['partially colored', 'partially coloured'],
  ['color', 'partially coloured'],

  ['un-censored', 'uncensored'],

  ['oral', 'blowjob'],
  ['fellatio', 'blowjob'],
  ['blow job', 'blowjob'],
  ['double fellatio', 'multiple blowjob'],
  ['throat fucking', 'deepthroat'],
  ['deep throat', 'deepthroat'],

  ['oppai', 'boobjob'],
  ['paizuri', 'boobjob'],
  ['mammary intercourse', 'boobjob'],
  ['tits-fuck', 'boobjob'],
  ['boob job', 'boobjob'],
  ['boobs job', 'boobjob'],
  ['multiple paizuri', 'multiple boobjob'],
  ['blonde.boob job', 'boobjob'],
  ['rimming', 'rimjob'],
  ['analingus (rimjob)', 'rimjob'],
  ['foot licking', 'foot fetish'],
  ['foot job', 'footjob'],

  ['hand job', 'handjob'],
  ['hairy armpit', 'hairy armpits'],
  ['hypnotism', 'hypnosis'],

  ['group', 'group sex'],
  ['group intercourse', 'group sex'],

  ['onani', 'masturbation'],

  ['heart pupils', 'heart-eyes'],
  ['symbol shaped pupils', 'unusual pupils'],
  ['sumata', 'thigh sex'],

  ['big breast', 'big breasts'],
  ['big boob', 'big breasts'],
  ['big boobs', 'big breasts'],
  ['busty', 'big breasts'],
  ['large breast', 'big breasts'],
  ['large breasts', 'big breasts'],
  ['huge boobs', 'big breasts'],
  ['huge breasts', 'big breasts'],
  ['gigantic breasts', 'big breasts'],
  ['bakunyuu', 'big breasts'],
  ['booty', 'big ass'],

  ['female dominance', 'femdom'],
  ['submission', 'femdom'],
  ['male dominance', 'domination'],
  ['maledom', 'domination'],
  ['sexually dominant', 'domination'],

  ['threesome (mff)', 'ffm threesome'],
  ['threesome (mmf)', 'mmf threesome'],
  ['threesome with sisters', 'ffm threesome'],
  ['threesome (other)', 'threesome'],
  ['lolicon', 'loli'],
  ['low lolicon', 'loli'],
  ['shotacon', 'shota'],

  ['pantyhose', 'tights'],
  ['milfs', 'milf'],
  ['mother', 'milf'],
  ['grandmother', 'gilf'],
  ['anal play', 'anal'],

  ['kogal', 'gyaru'],
  ['tanlines', 'tan lines'],
  ['tanned', 'dark skin'],
  ['dark-skinned girl', 'dark skin'],
  ['happy sex', 'wholesome'],
  ['romance', 'wholesome'],

  ['vampire', 'demi-human'],
  ['brother and sister', 'incest'],
  ['brother-sister incest', 'incest'],
  ['mother-son incest', 'incest'],
  ['father-daughter incest', 'incest'],
  ['sister-sister incest', 'incest'],
  ['father and daughter', 'incest'],
  ['mother and son', 'incest'],
  ['sister', 'incest'],
  ['sisters', 'incest'],
  ['older sister', 'incest'],

  ['swimsuite', 'swimsuit'],
  ['swimsuit/s', 'swimsuit'],
  ['bikini', 'swimsuit'],

  ['virign', 'defloration'],
  ['virgin', 'defloration'],
  ['virgins', 'defloration'],
  ['virginity', 'defloration'],
  ['deflowering', 'defloration'],

  ['housewife-housewives', 'housewife'],
  ['housewives', 'housewife'],
  ['nurses', 'nurse'],
  ['murse', 'nurse'],
  ['maids', 'maid'],
  ['nuns', 'nun'],
  ['office ladies', 'office lady'],
  ['school girls', 'school girl'],
  ['school-girls', 'school girl'],
  ['schoolgirl', 'school girl'],
  ['schoolgirls', 'school girl'],
  ['female student', 'school girl'],
  ['female teacher', 'teacher'],
  ['horny-slut', 'slut'],
  ['sluts', 'slut'],
  ['delinquents', 'delinquent'],
  ['waitresses', 'waitress'],
  ['witches', 'witch'],
  ['rich girl', 'ojousama'],
  ['princesses', 'princess'],
  ['teachers', 'teacher'],
  ['slavery', 'slave'],
  ['sex slaves', 'slave'],
  ['monsters', 'monster'],
  ['bunny girls', 'bunny girl'],

  ['schoolgirl outfit', 'school girl uniform'],
  ['schoolgirl uniform', 'school girl uniform'],

  ['monster girls', 'monster girl'],
  ['cat girls', 'cat girl'],
  ['catgirl', 'cat girl'],
  ['demon', 'demi-human'],
  ['demon girl', 'demi-human'],
  ['demon girls', 'demi-human'],
  ['majin', 'demi-human'],
  ['juujin', 'demi-human'],
  ['elf-elves', 'elf'],

  ['outdoor intercourse', 'public sex'],
  ['outdoor sex', 'public sex'],
  ['facesitting', 'face sitting'],
  ['bukakke', 'bukkake'],

  ['toys', 'sex toys'],
  ['dildos - vibrators', 'sex toys'],
  ['vibrator', 'sex toys'],
  ['hidden vibrator', 'sex toys'],
  ['sex toy', 'sex toys'],
  ['strapon', 'strap-on'],

  ['orgy', 'group sex'],
  ['gang bang', 'gang-bang'],
  ['gangbang', 'gang-bang'],
  ['ganggang', 'gang-bang'],

  ['zettai ryouiki', 'thigh highs'],
  ['stocking', 'stockings'],

  ['nakadashi', 'creampie'],
  ['cream pie', 'creampie'],

  ['internal shots', 'x-ray'],
  ['plot continuity', 'story arc'],
  ['plot', 'story arc'],
  ['porn with plot', 'story arc'],
  ['plot with porn', 'story heavy'],

  ['chikan', 'groping'],
  ['molestation', 'groping'],
  ['filmed', 'filming'],
  ['sex tape', 'filming'],
  ['golden shower', 'urination'],
  ['piss drinking', 'urination'],

  ['safer sex', 'condom'],
  ['double-penatration', 'double penetration'],

  ['ntr', 'netorare'],
  ['netorera', 'netorare'],

  ['sixty nine', 'sixty-nine'],
  ['69', 'sixty-nine'],

  ['drug', 'drugs'],
  ['guy getting raped', 'rape (female aggressor)'],
  ['reverse rape', 'rape (female aggressor)'],
  ['rape.yuri', 'rape (female on female)'],
  ['forced', 'rape'],
  ['forced sex', 'rape'],
  ['megane', 'glasses'],

  ['stomach deformation', 'distention'],
  ['hot springs visit', 'hot springs'],

  ['kunoichi (ninja girls)', 'kunoichi'],
  ['ninja', 'kunoichi'],

  ['cum swap', 'cum play'],
  ['cum swapping', 'cum play'],
  ['girls only', 'yuri'],
  ['females only', 'yuri'],

  ['mind contro', 'mind control'],
  ['tentacles', 'tentacle'],

  ['coslay', 'cosplay'],
  ['cosplaying', 'cosplay'],
  ['miko', 'shrine miko'],
  ['muscle', 'muscles'],

  ['twin tail', 'twintails'],
  ['twin tails', 'twintails'],
  ['adultery', 'cheating'],
  ['brides', 'bride'],

  ['enema play', 'enema'],
  ['bestiality', 'beastiality'],
  ['dickgirl on male', 'futa x male'],
  ['cross-dressing', 'crossdressing'],

  ['exhibition', 'exhibitionism'],
  ['pregnancy', 'pregnant'],
  ['drunk intercourse', 'drunk'],
  ['lacation', 'lactaion'],

  ['first person perspective', 'pov'],
  ['piercing', 'piercings']
]);
